name: our_portfolio
description: "A website to show our work and skills"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_storage: ^2.1.1
  get: ^4.6.6
  lottie: ^3.1.2
  video_player: ^2.9.1
  http: ^1.2.2
  cupertino_icons: ^1.0.6
  flutter_lints: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.13.1"
flutter_launcher_icons:
      web:
        generate: true
        image_path: "assets/logo/logotab.png"
#        background_color: "#hexcode"
#        theme_color: "#hexcode"

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/projects/
    - assets/contacts/
    - assets/availability/
    - assets/skills/
    - assets/platform/
    - assets/gif/
    - assets/logo/
    - assets/background_video/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
